### ISSUE TITLE
Outdated Mozilla.org URL on this Github repo

### ISSUE THREAD

**Issue by jaller94** [WebThingsIO/schemas#77]
The URL in the about section of this repo should be updated to https://webthings.io/schemas/

![Screenshot 2022-02-11 at 00-17-52 COAlarm Capability Schema · Issue #39 · WebThingsIO schemas](https://user-images.githubusercontent.com/10872136/153513149-741675f0-84dd-4693-8833-0b705025db98.png)

**Comment by benfrancis** [comment]
Done, thanks!
